# Generated by Django 5.2.8 on 2026-03-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_grade_created_at_grade_updated_at_school_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolregistration',
            old_name='phone',
            new_name='school_contact',
        ),
        migrations.RenameField(
            model_name='schoolregistration',
            old_name='email',
            new_name='school_email',
        ),
        migrations.RemoveField(
            model_name='schoolregistration',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='schoolregistration',
            name='message',
        ),
        migrations.AddField(
            model_name='schoolregistration',
            name='school_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolregistration',
            name='school_affiliation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schoolregistration',
            name='school_gst_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='schoolregistration',
            name='school_principal_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='schoolregistration',
            name='school_principal_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='schoolregistration',
            name='school_principal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schoolregistration',
            name='school_trust',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schoolregistration',
            name='school_website',
            field=models.URLField(blank=True),
        ),
    ]
