# Generated by Django 5.2.8 on 2025-11-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_user_school_staffprofile_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
