# Generated by Django 5.2.8 on 2026-04-01 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_phone_schoolregistration_school_contact_and_more'),
        ('learning', '0002_answeroption_created_at_answeroption_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.casestudy')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'unique_together': {('school', 'case_study')},
            },
        ),
    ]
