# Generated by Django 5.2.8 on 2026-04-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_casestudyaccess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='casestudy',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
