from django.urls import path
from .views import (
    AdminAnswerOptionDetailAPIView,
    AdminAnswerOptionListCreateAPIView,
    AdminCaseStudyDetailAPIView,
    AdminCaseStudyListCreateAPIView,
    AdminQuestionDetailAPIView,
    AdminQuestionListCreateAPIView,
    AdminServiceDetailAPIView,
    AdminServiceListCreateAPIView,
    AdminTheoryTopicListCreateAPIView,
    AdminUserDetailAPIView,
    AdminUserListAPIView,
    AdminUserResetPasswordAPIView,
    AdminUserStatusAPIView,
    ApproveSchoolRegistrationAPIView,
    BulkQuestionUploadAPIView,
    BulkTheoryTopicUploadAPIView,
    RejectSchoolRegistrationAPIView,
    SchoolRegistrationListAPIView,
    SuperAdminDashboardAPIView,
    SchoolListAPIView,
    SchoolDetailAPIView,
    SchoolStatusUpdateAPIView,
    SchoolAnalyticsAPIView,
    AdminTheoryTopicDetailAPIView,
    BulkOptionUploadAPIView,
    BulkCaseStudyUploadAPIView,
    AdminGradeListAPIView,
    ToggleCaseStudyLockAPIView
)

urlpatterns = [
    path("dashboard/", SuperAdminDashboardAPIView.as_view()),
    path("schools/", SchoolListAPIView.as_view()),
    path("schools/<int:school_id>/", SchoolDetailAPIView.as_view()),
    path("schools/<int:school_id>/status/", SchoolStatusUpdateAPIView.as_view()),
    path("schools/<int:school_id>/analytics/", SchoolAnalyticsAPIView.as_view()),
    path("school-registrations/", SchoolRegistrationListAPIView.as_view()),
    path("school-registrations/<int:registration_id>/approve/",ApproveSchoolRegistrationAPIView.as_view(),),
    path("school-registrations/<int:registration_id>/reject/",RejectSchoolRegistrationAPIView.as_view(),),
    path("users/", AdminUserListAPIView.as_view()),
    path("users/<int:user_id>/", AdminUserDetailAPIView.as_view()),
    path("users/<int:user_id>/status/", AdminUserStatusAPIView.as_view()),
    path("users/<int:user_id>/reset-password/", AdminUserResetPasswordAPIView.as_view()),
    path("services/", AdminServiceListCreateAPIView.as_view()),
    path("services/<int:pk>/", AdminServiceDetailAPIView.as_view()),
    path("theory-topics/", AdminTheoryTopicListCreateAPIView.as_view()),
    path("theory-topics/<int:pk>/", AdminTheoryTopicDetailAPIView.as_view()),
    path("case-studies/", AdminCaseStudyListCreateAPIView.as_view()),
    path("case-studies/<int:pk>/", AdminCaseStudyDetailAPIView.as_view()),
    path("questions/", AdminQuestionListCreateAPIView.as_view()),
    path("questions/<int:pk>/", AdminQuestionDetailAPIView.as_view()),
    path("options/", AdminAnswerOptionListCreateAPIView.as_view()),
    path("options/<int:pk>/", AdminAnswerOptionDetailAPIView.as_view()),
    path("bulk/questions/", BulkQuestionUploadAPIView.as_view()),
    path("bulk/options/", BulkOptionUploadAPIView.as_view()),
    path("bulk/theory-topics/", BulkTheoryTopicUploadAPIView.as_view()),
    path("bulk/case-studies/", BulkCaseStudyUploadAPIView.as_view()),
    # path("services/", AdminServiceListCreateAPIView.as_view()),
    path("grades/", AdminGradeListAPIView.as_view()),
    path("case-studies/toggle-lock/", ToggleCaseStudyLockAPIView.as_view()),
]
